### ISSUE TITLE
ReadMe needs to be updated to swift 3

### ISSUE THREAD

**Issue by keatonharward** [DevMountain/Alarm#3]

**Comment by niclaughter** [comment]
In ControllerBasics, the follow lines reflect an update:
```Create an addAlarm(fireTimeFromMidnight: TimeInterval, name: String) function that creates an alarm, adds it to the alarms array, and returns the alarm.```
```Create an updateAlarm(alarm: Alarm, fireTimeFromMidnight: TimeInterval, name: String) function that updates an existing alarm's fire time and name.```

**Comment by niclaughter** [comment]
There also needs to be something about setting the alarm cell's reuse identifier.

**Comment by niclaughter** [comment]
The `delegate` protocol is titled incorrectly in the note:

```Add a protocol named #SwitchTableViewCellDelegate# to the bottom of the SwitchTableViewCell class file```
```Define a required switchCellSwitchValueChanged(cell: SwitchTableViewCell) function```
```Add a weak, optional delegate property on the SwitchTableViewCell, require the delegate to have adopted the delegate protocol```
```note: weak var delegate: #ButtonTableViewCellDelegate#?```

**Comment by armadsen** [comment]
That commit (82ca4a9) updates the README. Would love a review from either of you.

**Comment by niclaughter** [comment]
Looks great to me.
